language: python
env:
    - PYTHON=2.7
    - PYTHON=3.5
before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=$PYTHON
    - source activate testenv
    - conda install --yes --quiet numpy=1.11 scipy=0.17 scikit-learn=0.18 pytest pytest-cov pandas coverage
    - pip install flake8 codecov
    - python setup.py develop
script:
    - py.test --cov=pyglmnet tests/
    - flake8 --count pyglmnet
after_success:
    - bash <(curl -s https://codecov.io/bash)
