version: 2
jobs:
    build_docs:
        docker:
            - image: circleci/python:3.7.0-stretch-node-browsers
        steps:
            - checkout
            - run:
                name: Install miniconda
                command: |
                  wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh;
                  chmod +x ~/miniconda.sh;
                  ~/miniconda.sh -b -p ~/miniconda;
                  echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
            - run:
                name: Setup Python environment
                command: |
                    conda update --yes conda
                    conda create -n testenv --yes python=3.7
                    source activate testenv
                    pip install --upgrade pip -q
                    pip install sphinx matplotlib coverage Pillow -q
                    pip install sphinx-gallery -q
                    pip install scipy scikit-learn pandas -q
                    pip install -e .
                    pip install sphinx_bootstrap_theme numpydoc -q
                    pip install -e git+http://github.com/KordingLab/spykes.git#egg=spykes
                    python -c "import pyglmnet; pyglmnet.datasets.fetch_rgc_data('examples/glm-data', accept_rgcs_license=True);"
                    python --version
                    pip list
            - run:
                name: Build the documentation
                command: |
                    source activate testenv
                    cd doc && make html
                no_output_timeout: 30m
            - store_artifacts:
                path: doc/_build/html/
                destination: html

workflows:
  version: 2
  search_build:
    jobs:
      - build_docs
